name: Tests

on:
  push:
    branches:
      - main
      - dev
      - master

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo Welcome to the Github Actions workshop !

  unit_test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: make tests_run
      - name: Get Coverage
        if: ${{ always() }}
        run: make coverage > coverage_outputs
      - name: Upload coverage artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage_outputs
          path: ./coverage_outputs

  function_test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run functional tests
        if: ${{ always() }}
        run: make && ./functional-test.sh > function-tests_outputs
      - name: Upload coverage artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: function-tests_outputs
          path: ./function-tests_outputs