name: Tests

on:
  push:
    branches:
      - main
      - dev
      - master

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo Welcome to the Github Actions workshop !

  unit_test:
    runs-on: ubuntu-20.04
    container: docker://epitechcontent/epitest-docker
    steps:
      - run: mkdir -p path/to/artifact && cd path/to/artifact && touch world.txt
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
      - name: Checkout
        uses: actions/checkout@v2 > path/to/artifact/world.txt
      - name: Run tests
        run: make tests_run > path/to/artifact/world.txt
      - name: Get Coverage
        run: make coverage > path/to/artifact/world.txt