name: Tests

on:
  push:
    branches:
      - main
      - dev
      - master

jobs:
  hello-world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello world
        run: echo Welcome to the Github Actions workshop !
  unit_test:
    runs-on: ubuntu-20.04
    steps:
      - name: check and unit_tests and coverage
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
        run: make tests_run && make coverage